global:
  scrape_interval: 15s

scrape_configs:
  - job_name: nest-online-shop
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /api/v1/metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'nest-online-shop:3000'
